name: dorm_example
description: A sample command-line application for the DORM Client package.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  json_annotation: ^4.8.0
  dorm_client:
    path: ..

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
